name: Simple CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run a basic test
        run: echo "CI Pipeline Running!"
      - name: Run tests
        run: bash scripts/test_script.sh
      - name: Run Unit Tests
        run: pytest test_example.py