name: Security Scan
on: [push, pull_request]
jobs:
   scan:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v3
         - name: Install Trivy
           run: |
             sudo apt-get install wget -y
             wget
https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.38.3_L
inux-64bit.tar.gz
             tar -zxvf trivy_0.38.3_Linux-64bit.tar.gz
             sudo mv trivy /usr/local/bin/
         - name: Scan Docker image for vulnerabilities
           run: trivy fs .
